Repository avinashkranjan/Recess, pull requests merged in 2021-04, with the labels that each got.

#137 New design
  .firebase/hosting.YnVpbGQ.cache
  .firebaserc
  firebase.json
  public/icon.ico
  public/index.html
  src/App.css
  src/App.js
  src/assets/contracted-logo.png
  src/assets/logo.png
  src/components/AuthForms/index.js
  src/components/AuthForms/style.js
  src/components/BottomNavBar/index.js
  src/components/BottomNavBar/style.js
  src/components/Footer/index.js
  src/components/Footer/style.css
  src/components/Header/index.js
  src/components/Header/style.js
  src/components/ImageUploader/index.js
  src/components/ImageUploader/style.css
  src/components/Post/index.js
  src/components/Post/style.css
  src/components/Post/style.js
  src/components/Sidebar/SideBarData.js
  src/components/Sidebar/index.js
  src/components/Sidebar/style.css
  src/components/Sidebar/style.js
  src/index.css
  src/index.js
  src/pages/ExplorePage/index.js
  src/pages/ExplorePage/style.js
  src/pages/HomePage/index.js
  src/pages/HomePage/style.css
  src/pages/NotFoundPage/index.js
  src/pages/NotFoundPage/style.js
  src/pages/PostPage/index.js
  src/pages/PostPage/style.js
  src/pages/UnderDevPage/index.js
  src/pages/UnderDevPage/style.js
  src/pages/UploadPage/index.js
  src/pages/UploadPage/style.css
  src/pages/UploadPage/style.js
  src/style.js
  src/theme.js
Labels: Approved, GSSOC21, Level3

#158 Hiding Comments and Creating Modal to show all Comments Issue #146
  src/components/Post/index.js
  src/components/Post/style.js
Labels: Approved, GSSOC21, Level2

#147 feat(theme): added persistence of user selected theme
  src/App.js
  src/components/Header/index.js
  src/components/Sidebar/index.js
Labels: Approved, GSSOC21, Level2

#159 google authentication added
  package.json
  src/components/AuthForms/index.js
  src/components/AuthForms/style.js
  src/firebase.js
Labels: Approved, GSSOC21, Level3

#160 Modal to show all comments Issue #146
  src/components/Post/index.js
  src/components/Post/style.js
  src/pages/HomePage/index.js
  src/pages/HomePage/style.js
Labels: Approved, GSSOC21, Level3

#169 added popup message, will time out after 5 secs!
  src/pages/HomePage/index.js
Labels: Approved, GSSOC21, Level3

#173 auto merge the PR from dependabot
  .github/workflows/automerge.yml
Labels: Approved, GSSOC21, Level2

#187 Welcome bot added
  .github/workflows/greetings.yml
Labels: GSSOC21, Level1

#178 Added auto reply for every successful merged pull requests
  .github/workflows/Auto_Reply_On_Merge.yml
Labels: Approved, GSSOC21, Level2
