Repository avinashkranjan/Recess, pull requests merged in 2021-06, with the labels that each got.

#219 Fixed double post & code refactored
  src/pages/HomePage/index.js
Labels: GSSOC21, Level2

#220 Implemented Display picture from socials
  src/App.js
  src/components/LikePanel/index.js
  src/components/Post/index.js
  src/components/Sidebar/index.js
  src/pages/HomePage/index.js
  src/pages/PostPage/index.js
  src/pages/UploadPage/index.js
Labels: GSSOC21, Level2

#210 Splash screen addition#164
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/assets/img.png
Labels: Approved, GSSOC21, Level3, hold

#174 Svg morphing animation Issue #166
  package-lock.json
  package.json
  src/components/Header/index.js
Labels: GSSOC21, Level2

#194 About page routing added
  src/App.js
  src/components/Sidebar/index.js
  src/pages/AboutPage/index.js
  src/pages/AboutPage/style.js
Labels: GSSOC21, Level3
