Repository avinashkranjan/Recess, pull requests merged in 2021-03, with the labels that each got.

#62 Restructured Files
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/pages/Homepage.css
  src/pages/Homepage.js
Labels: GSSOC21, Level 1

#94 update contributing.md
  CONTRIBUTING.md
Labels: Approved, GSSOC21, Level0

#93 Issue 87: Footer Added
  package-lock.json
  src/pages/Footer.css
  src/pages/Footer.js
  src/pages/Homepage.js
Labels: Approved, GSSOC21, Level2

#78 Added a pull request template
  .github/pull_request_template.md
Labels: Approved, GSSOC21, Level1

#85 Added welcome bot
  .github/config.yml
Labels: Approved, GSSOC21, Level1

#90 Changes made in Navigation Bar-Issue#77 Addressed
  src/pages/Homepage.css
  src/pages/Homepage.js
Labels: Approved, GSSOC21, Level2

#86 Issue #53 Implementation for side navigation bar
  package-lock.json
  package.json
  src/ImageUpload.css
  src/SideBarData.js
  src/Sidebar.css
  src/Sidebar.js
  src/pages/Homepage.js
Labels: Approved, GSSOC21

#92 Added Dark Mode and Restructured Files
  .eslintcache
  .gitignore
  package-lock.json
  src/App.css
  src/App.js
  src/SideBarData.js
  src/Sidebar.js
  src/assets/logo.png
  src/components/Footer/index.js
  src/components/Footer/style.css
  src/components/ImageUploader/index.js
  src/components/ImageUploader/style.css
  src/components/Post/index.js
  src/components/Post/style.css
  src/components/Sidebar/SideBarData.js
  src/components/Sidebar/index.js
  src/components/Sidebar/style.css
  src/pages/Footer.css
  src/pages/Footer.js
  src/pages/HomePage/index.js
  src/pages/HomePage/style.css
  src/pages/Homepage.css
  src/pages/Homepage.js
Labels: Approved, GSSOC21, Level3

#114 Modified the UI of Upload Form
  package-lock.json
  src/components/ImageUploader/index.js
  src/components/ImageUploader/style.css
Labels: Approved, GSSOC21, Level2, enhancement

#129 GSSoC
  .github/workflows/main.yml
Labels: Approved, GSSOC21

#144 Added auto label for issues
  .github/workflows/issue.yml
Labels: GSSOC21, Level1

#116 Added Profile page and routing
  src/App.js
  src/SideBarData.js
  src/Sidebar.css
  src/Sidebar.js
  src/pages/Footer.css
  src/pages/Footer.js
  src/pages/Homepage.css
  src/pages/Homepage.js
  src/pages/ProfilePage/index.js
  src/pages/ProfilePage/style.css
Labels: GSSOC21, Level3, enhancement

#149 fix(logo): added logo redirection to home
  src/pages/HomePage/index.js
Labels: GSSOC21, Level1

#123 Added Not Found and Under Dev Page components
  src/App.js
  src/SideBarData.js
  src/Sidebar.css
  src/Sidebar.js
  src/assets/not-found-art.png
  src/assets/under-dev-art.png
  src/components/ImageUploader/index.js
  src/components/ImageUploader/style.css
  src/components/Sidebar/SideBarData.js
  src/components/Sidebar/index.js
  src/pages/Footer.css
  src/pages/Footer.js
  src/pages/HomePage/index.js
  src/pages/Homepage.css
  src/pages/Homepage.js
  src/pages/NotFoundPage/index.js
  src/pages/NotFoundPage/style.js
  src/pages/ProfilePage/style.css
  src/pages/UnderDevPage/index.js
  src/pages/UnderDevPage/style.js
  src/pages/UploadPage/index.js
  src/pages/UploadPage/style.css
Labels: Approved, GSSOC21, Level3, enhancement
