Repository avinashkranjan/Recess, pull requests merged in 2021-05, with the labels that each got.

#212 Added like and dislike functionality #125
  src/components/LikePanel/index.js
  src/components/LikePanel/style.js
  src/components/Post/index.js
  src/components/Post/style.js
  src/pages/PostPage/index.js
Labels: Approved

#203 github authentication added
  src/components/AuthForms/index.js
  src/components/AuthForms/style.js
  src/firebase.js
Labels: Approved, GSSOC21, Level2, enhancement

#209 facebook authentication added
  src/components/AuthForms/index.js
  src/components/AuthForms/style.js
  src/firebase.js
Labels: Approved, GSSOC21, Level3, enhancement

#214 twitter auth added
  src/components/AuthForms/index.js
  src/components/AuthForms/style.js
  src/firebase.js
Labels: GSSOC21, Level2
